
-- Database Setup

CREATE DATABASE BANK;
USE BANK;

-- Initial Data Exploration

SELECT * FROM LOANS LIMIT 5;

SELECT COUNT(*) FROM LOANS;

SELECT ROUND(AVG(DEFAULT_IND), 3) AS DEFAULT_RATE FROM LOANS;

-- Default Rate Analysis

-- Default rate by grade
SELECT GRADE, ROUND(AVG(DEFAULT_IND), 3) AS DEFAULT_RATE 
FROM LOANS
GROUP BY GRADE
ORDER BY DEFAULT_RATE DESC;

-- Default rate by income group
SELECT CASE WHEN ANNUAL_INC < 50000 THEN 'Low'
            WHEN ANNUAL_INC < 100000 THEN 'Medium'
	        ELSE 'High'
	   END AS INCOME_GROUP, 
       ROUND(AVG(`DEFAULT_IND`), 3) AS DEFAULT_RATE 
FROM LOANS
GROUP BY CASE WHEN ANNUAL_INC < 50000 THEN 'Low'
            WHEN ANNUAL_INC < 100000 THEN 'Medium'
	        ELSE 'High'
	   END;

-- High Risk Identification

-- Filter high-risk customers
SELECT * FROM LOANS WHERE DTI > 30 AND INT_RATE > 15 AND ANNUAL_INC < 50000;

-- High-risk count and default rate 
SELECT COUNT(*) AS HIGH_RISK_CUSTOMERS, ROUND(AVG(DEFAULT_IND), 3) AS DEFAULT_RATE FROM LOANS WHERE DTI > 25  AND INT_RATE > 13;

-- High vs Normal segmentation
SELECT CASE WHEN DTI > 25 AND INT_RATE > 13 THEN 'High Risk' ELSE 'Normal' END AS SEGMENT, ROUND(AVG(DEFAULT_IND), 3) AS DEFAULT_RATE
FROM LOANS GROUP BY SEGMENT;

-- Loan & Customer Segmentation

-- Loan size segmentation
SELECT CASE WHEN LOAN_AMNT < 5000 THEN 'Small' WHEN LOAN_AMNT < 15000 THEN 'Medium' ELSE 'Large' END AS LOAN_SIZE, 
ROUND(AVG(DEFAULT_IND), 3) AS DEFAULT_RATE FROM LOANS GROUP BY LOAN_SIZE;

-- Home ownership impact
SELECT HOME_OWNERSHIP, ROUND(AVG(DEFAULT_IND), 3) AS DEFAULT_RATE FROM LOANS GROUP BY HOME_OWNERSHIP;

-- Loan purpose analysis
SELECT PURPOSE, ROUND(AVG(DEFAULT_IND), 3) AS DEFAULT_RATE FROM LOANS GROUP BY PURPOSE ORDER BY DEFAULT_RATE DESC LIMIT 5;

-- Risk score analysis
SELECT RISK_SCORE, ROUND(AVG(DEFAULT_IND), 3) AS DEFAULT_RATE FROM LOANS GROUP BY RISK_SCORE ORDER BY RISK_SCORE DESC;

-- Risk Segmentation Analysis
SELECT CASE WHEN DTI > 25 AND INT_RATE > 13 THEN 'High Risk' WHEN DTI > 20 THEN 'Medium Risk' ELSE 'Low Risk' END AS RISK_SEGMENT, 
COUNT(*) AS CUSTOMERS, ROUND(AVG(DEFAULT_IND), 3) AS DEFAULT_RATE FROM LOANS GROUP BY RISK_SEGMENT ORDER BY DEFAULT_RATE DESC;

-- Top Risky Customers
SELECT ID, LOAN_AMNT, INT_RATE, DTI, ANNUAL_INC, DEFAULT_IND FROM LOANS ORDER BY DTI DESC, INT_RATE DESC LIMIT 10;

-- Combined Analysis
SELECT GRADE, CASE WHEN ANNUAL_INC < 50000 THEN 'Low' WHEN ANNUAL_INC < 100000 THEN 'Medium' ELSE 'High' END AS INCOME_GROUP,
ROUND(AVG(DEFAULT_IND), 3) AS DEFAULT_RATE FROM LOANS GROUP BY GRADE, 
CASE WHEN ANNUAL_INC < 50000 THEN 'Low' WHEN ANNUAL_INC < 100000 THEN 'Medium' ELSE 'High' END
ORDER BY GRADE, DEFAULT_RATE DESC;

-- Advanced SQL (Window Functions)

-- Risk ranking
SELECT ID, LOAN_AMNT, INT_RATE, DTI, RANK() OVER (ORDER BY DTI DESC, INT_RATE DESC) AS RISK_RANK FROM LOANS;

-- Cumulative default rate
SELECT LOAN_AMNT, ROUND(AVG(DEFAULT_IND) OVER(ORDER BY LOAN_AMNT), 3) AS CUMULATIVE_DEFAULT_RATE FROM LOANS;

-- Income Band Analysis
SELECT FLOOR(ANNUAL_INC/20000)*20000 AS INCOME_BAND, ROUND(AVG(DEFAULT_IND), 3) AS DEFAULT_RATE
FROM LOANS
GROUP BY INCOME_BAND
ORDER BY INCOME_BAND;

-- Expected Defaults
SELECT GRADE, COUNT(*) AS TOTAL_LOANS, ROUND(COUNT(*) * AVG(DEFAULT_IND), 2) AS EXPECTED_DEFAULTS 
FROM LOANS GROUP BY GRADE ORDER BY EXPECTED_DEFAULTS DESC;

-- Interest Rate Impact
SELECT CASE WHEN INT_RATE > 15 THEN 'High Interest' ELSE 'Low Interest' END AS INTEREST_GROUP, ROUND(AVG(DEFAULT_IND), 3) AS DEFAULT_RATE 
FROM LOANS GROUP BY INTEREST_GROUP;

-- Views & Summary Tables
CREATE VIEW HIGH_RISK_CUSTOMERS AS SELECT * FROM LOANS WHERE DTI > 25 AND INT_RATE > 13;

CREATE TABLE RISK_SUMMARY AS SELECT GRADE, COUNT(*) AS TOTAL_LOANS, ROUND(AVG(DEFAULT_IND), 3) AS DEFAULT_RATE FROM LOANS GROUP BY GRADE;

SELECT * FROM RISK_SUMMARY;
